spring.datasource.url=jdbc:sqlite:cache.db

server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=theo
spring.rabbitmq.password=theo
spring.rabbitmq.exchange=libraryapp.direct

cacheapp.rabbitmq.updatequeue=cacheapp.queue.updates
cacheapp.rabbitmq.requestqueue=cacheapp.queue.requests

cacheapp.rabbitmq.routingkey.responses=cacheapp.responses