spring.datasource.url=jdbc:sqlite:books.db

server.port=8080

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=theo
spring.rabbitmq.password=theo
spring.rabbitmq.exchange=libraryapp.direct

libraryapp.rabbitmq.responsequeue=libraryapp.queue.responses

libraryapp.rabbitmq.routingkey.requests=libraryapp.requests
libraryapp.rabbitmq.routingkey.updates=libraryapp.updates