spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=theo
spring.rabbitmq.password=theo
libraryapp.rabbitmq.queue=libraryapp.queue1
libraryapp.rabbitmq.exchange=libraryapp.direct
libraryapp.rabbitmq.routingkey=libraryapp.routingkey