spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=theo
spring.rabbitmq.password=theo
restaurantapp.rabbitmq.queue=restaurantapp.queue1
restaurantapp.rabbitmq.exchange=restaurantapp.direct
restaurantapp.rabbitmq.routingkey=restaurant.routingkey